### ISSUE TITLE
Builds successfully, but crashes immediately when run

### ISSUE THREAD

**Issue by frugs** [Delta-Icons/android#22]
I managed to build the APK, but it crashes as soon as I try to run it. Here's the stacktrace:

```
10-09 18:17:37.869 401-401/website.leifs.delta E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: website.leifs.delta, PID: 401
                                                                 java.lang.RuntimeException: Unable to instantiate application website.leifs.delta.applications.CandyBar: java.lang.ClassNotFoundException: Didn't find class "website.leifs.delta.applications.CandyBar" on path: DexPathList[[zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/base.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_dependencies_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_0_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_1_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_2_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_3_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_4_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_5_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_6_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_7_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_8_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:971)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5787)
                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                     at android.os.Looper.loop(Looper.java:251)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6563)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "website.leifs.delta.applications.CandyBar" on path: DexPathList[[zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/base.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_dependencies_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_0_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_1_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_2_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_3_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_4_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_5_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_6_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_7_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_8_apk.apk", zip file "/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/website.leifs.delta-t6GUMU3n2h3ZRVopWNlinA==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
                                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:965)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5787) 
                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                     at android.os.Looper.loop(Looper.java:251) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6563) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by leifniem** [comment]
This may be because i did not include the License class for safety measures.
If you could shoot me a mail i can give you instructions on how to build your own build.

**Comment by frugs** [comment]
If it's intentional, then that's fine! I'm still able to test my icon submissions without running the app.

**Comment by leifniem** [comment]
Okay great :) Thanks for your help!

**Comment by flameshikari** [comment]
> This may be because i did not include the License class for safety measures.
> If you could shoot me a mail i can give you instructions on how to build your own build.

Sorry for writing in a closed issue, but can you send me instructions too, please? I have the same issue as frugs.
